### ISSUE TITLE
metadata.rb is missing from supermarket copy?

### ISSUE THREAD

**Issue by andrewfraley** [sethvargo/chef-sugar#92] opened 2015-03-03 16:48 UTC
```
$> knife cookbook site install chef-sugar
Installing chef-sugar to /home/afraley/chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-chef-sugar) exists, switching to it.
Downloading chef-sugar from the cookbooks site at version 2.5.0 to /home/afraley/chef-repo/cookbooks/chef-sugar.tar.gz
Cookbook saved: /home/afraley/chef-repo/cookbooks/chef-sugar.tar.gz
Removing pre-existing version.
Uncompressing chef-sugar version 2.5.0.
removing downloaded tarball
No changes made to chef-sugar
Checking out the master branch.
ERROR: IOError: Cannot open or read /home/afraley/chef-repo/cookbooks/chef-sugar/metadata.rb!
```

**Comment by sethvargo** [comment] 2015-03-03 16:53
Duplicate of https://github.com/sethvargo/chef-sugar/issues/78. Please see my comment there :smile:

**Closed by sethvargo** 2015-03-03 16:53 UTC
