### ISSUE TITLE
chef-sugar in policyfile workflow

### ISSUE THREAD

**Issue by eeyun** [sethvargo/chef-sugar#114] opened 2015-09-03 20:35 UTC
Hey Seth!
Hope all is well, this may be a non-issue or it might be something that's outside of scope for chef-sugar but I discovered something today attempting to use chef-sugar while testing via an in-development policyfile workflow. I received the following error during compile (from a simple include_recipe 'chef-sugar' statement): 
```
ERROR:  Could not find a valid gem 'chef-sugar' (= 52672348151980847.32119188467372255.248863852452958) in any repository
ERROR:  Possible alternatives: chef-sugar
```
My immediate guess was that this is related to the chef-run context when using policyfiles? 

I was able to bypass the error by editing the chef-sugar recipe to install the latest version of the chef-sugar gem. So, I'm still doing testing, but I am assuming that anyone else that is using chef-sugar in the context of a policyfile will see the same thing.

Figured it was worth discussing!

**Comment by sethvargo** [comment] 2015-09-04 14:26
Ping @danielsdeleo

**Comment by danielsdeleo** [comment] 2015-09-04 14:58
@sethvargo are you pulling the cookbook version off the run context and then doing a gem install for that version or something like `gem "chef-sugar", detected_version; require 'chef-sugar'`?

**Comment by sethvargo** [comment] 2015-09-04 15:02
@danielsdeleo v

**Comment by danielsdeleo** [comment] 2015-09-04 16:44
Ugh, so it turns out that because of how chef-zero works, all of the "real version" information is lost. If you `chef push` with compatibility mode to a real chef server, the version number is actually kept in two places, one of them has to be the cookbook-hash-mapped-to-semver version number but the other one is the "real" version, but when we export everything as files for chef-zero to use, the version number is only in the metadata.json file, so we don't have the real version number any more.

The policyfile knows what the version number is, but there's no easy way to get a handle on that from inside a cookbook. It would be fairly easy to stash the policyfile on the run_context, which would let you introspect a lot of stuff in policyfile mode, but that would also require a change to the chef-sugar cookbook to support it. Thoughts?

**Comment by eeyun** [comment] 2015-09-04 18:15
A: Apologies I totally though I had tagged you in my original issue, Dan.
B: My opinion might be off base (or it might nonpertinent to the conversation) - but the pattern established by the chef-sugar recipe here (https://github.com/sethvargo/chef-sugar/blob/master/recipes/default.rb#L22-L32) really enables binding of the gem artifact and cookbook together in a particularly rad and useful way. So the only add I have to the dialogue is: I would really hope that any change made to the chef-sugar recipe would not break break *that* particularly.... Not sure if thats helpful.

**Comment by danielsdeleo** [comment] 2015-09-04 21:08
In the long term I think this problem just goes away when we can finally phase out "compatibility mode" everywhere. But that's a somewhat large undertaking to get chef-zero to support all the new APIs. What we can do quickly is, update chef-client to make the policyfile accessible via the run_context, which you should be able to do by adding a policyfile attribute to `RunContext` and setting that here: https://github.com/chef/chef/blob/530119278f6a71eef4b0bf02df022218a96dcecc/lib/chef/policy_builder/policyfile.rb#L157 Then chef-sugar would need to learn to check for policyfiles and if there is one, use that to get the version (here: https://github.com/sethvargo/chef-sugar/blob/ca47aaa83dd102dff940c6308b298ddca7434a1a/recipes/default.rb#L20).

Anyway, I think the trick of using the same cookbook and gem version is neat, but I just don't see a way to make it work aside from what I described.

**Comment by johnbellone** [comment] 2016-01-22 17:50
So for now this is unresolved?

**Comment by danielsdeleo** [comment] 2016-01-22 19:27
Not fixed yet, but we are making progress. The latest version of Chef Zero now has the "native" policyfile APIs (`policies`, `policy_groups`, and `cookbook_artifacts`). So with a correctly formatted chef repo, Chef Zero (and chef client local mode) can serve cookbooks for policyfiles without doing the version number mangling. To actually fix the problem, though, the behavior of the `chef export` command needs to be changed to create a chef repo with cookbook artifacts instead of cookbooks, etc. I'm working on that now.

**Comment by johnbellone** [comment] 2016-01-22 22:23
awesome! Thanks for the update Dan. 

Sent from my iPhone
JB

**Comment by danielsdeleo** [comment] 2016-02-16 23:00
I have confirmed that chef sugar works correctly with `chef export`/test kitchen as of the ChefDK 0.11 prerelease, which should be hitting GA release soon. Feel free to close this one according to whenever you close things.

**Closed** 2016-02-16 23:08 UTC
